# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

buggy_fun_impl <- function() {
    .Call(`_debugit_buggy_fun_impl`)
}

add_one_impl <- function(x) {
    .Call(`_debugit_add_one_impl`, x)
}

